services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - my-network
    volumes:
      - my-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  backend:
    image: mnindrazaka/backend
    container_name: backend
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-network
networks:
  my-network:
    name: my-network
volumes:
  my-volume:
    name: my-volume
