import React from "react";
import Head from "next/head";

type Biodata = {
  Id: number;
  Name: string;
};

export default function Home() {
  const [biodatas, setBiodatas] = React.useState<Biodata[]>([]);

  React.useEffect(() => {
    fetch("http://localhost:3000")
      .then((res) => res.json())
      .then((res: Biodata[]) => setBiodatas(res));
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ol>
        {biodatas.map(({ Id, Name }) => (
          <li key={Id}>{Name}</li>
        ))}
      </ol>
    </div>
  );
}
